name: helm-release
on:
  push:
    branches:
      - 'release-*'

jobs:
  create-release:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Install | AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip 
          sudo ./aws/install --update
      - name: Install | helm
        run: |
          HELM_VERSION=$(curl -Ls https://github.com/helm/helm/releases | grep 'href="/helm/helm/releases/tag/v3.[0-9]*.[0-9]*\"' | sed -E 's/.*\/helm\/helm\/releases\/tag\/(v[0-9\.]+)".*/\1/g' | head -1)
          sudo wget -q https://get.helm.sh/helm-$HELM_VERSION-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > helm
          sudo mv helm /usr/local/bin/helm
          sudo chmod +x /usr/local/bin/helm
      - name: Build | Login to ECR
        run: aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
      - name: Build | Package helm
        run: |
          helm package \
          charts/kyverno-notation-aws \
          --app-version ${GITHUB_SHA} \
          --version ${GITHUB_SHA}
      - name: Release | Helm Chart
        run : |
          helm push "kyverno-notation-aws-${GITHUB_SHA}.tgz" oci://${{ vars.ECR_REPOSITORY }}
        shell: bash
